apiVersion: v1
kind: Service
metadata:
  name: lo-web-frontend-service
spec:
  selector:
    app: lo-web-frontend
  ports:
    - name: lo-web-frontent-port
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer