apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharepoint-vm-pvc-0
  namespace: lo-dev-d6n4g
  labels:
    vm-selector: sharepoint-vm
  annotations:
    csi.vsphere.volume-requested-topology: '[{"topology.kubernetes.io/zone":"zone1"}]'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: vsan-default-storage-policy
