apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  name: sharepoint-vm
  namespace: lo-dev-d6n4g
  labels:
    vm-selector: sharepoint-vm
    sharepoint-vm-lb: vm-lb-selector
    topology.kubernetes.io/zone: zone1
spec:
  className: best-effort-large
  # Friendly image name: ubuntu-server-22.04-lts-jammy-jellyfish
  imageName: vmi-4fe028aed74014d97
  storageClass: vsan-default-storage-policy
  powerState: PoweredOn
  volumes:
    - name: sharepoint-vm-pvc-0
      persistentVolumeClaim:
        claimName: sharepoint-vm-pvc-0
  network:
    hostName: sharepoint-vm
    domainName: acme.com
    nameservers:
      - 192.168.10.10
    searchDomains:
      - acme.com
  bootstrap:
    sysprep:
      sysprep:
        guiUnattended:
          autoLogon: true
          password:
            name: sharepoint-vm-bootstrap-secret
            key: password
          autoLogonCount: 1
        userData:
          fullName: Administrator
          orgName: ACME
        guiRunOnce:
          commands:
            - >-
              # Install Windows features required for SharePoint

              Install-WindowsFeature Web-Server, Web-WebServer, Web-Common-Http,
              Web-Default-Doc, Web-Static-Content, `
                  Web-Http-Errors, Web-Http-Redirect, Web-Http-Logging, Web-Request-Monitor, Web-Http-Tracing, `
                  Web-Performance, Web-Stat-Compression, Web-Dyn-Compression, Web-Security, Web-Filtering, `
                  Web-Basic-Auth, Web-Windows-Auth, Web-Client-Auth, Web-Digest-Auth, Web-CertProvider, Web-Cert-Auth, `
                  Web-ISAPI-Ext, Web-ISAPI-Filter, Web-Mgmt-Console, Web-Mgmt-Compat, NET-Framework-Features, `
                  NET-Framework-45-Core, NET-Framework-45-ASPNET, NET-WCF-Services45, NET-WCF-HTTP-Activation45, `
                  Server-Media-Foundation, Application-Server, App-Server, WAS, WAS-Process-Model, `
                  WAS-NET-Environment, WAS-Config-APIs -IncludeManagementTools -Restart
              # Silent SharePoint 2019 installation

              .\setup.exe /config D:\Files\config.xml
        identification:
          joinDomain: acme.com
          domainAdmin: administrator
          domainAdminPassword:
            name: sharepoint-vm-bootstrap-secret
            key: domainAdminPassword
